return {
  icons = {
    diagnostics = {
      -- error = ' ',
      -- warning = ' ',
      -- info = ' ',
      -- hint = ' ',
      -- ok = ' ',
      error = '■',
      warning = '■',
      info = '■',
      hint = '■',
      ok = '■',
    },
    git = {
      unstaged = '~',
      staged = '+',
      unmerged = '',
      renamed = '➜',
      untracked = '★',
      deleted = '',
      ignored = '◌',
    },
    dap = {
      breakpoint = '🛑',
      breakpoint_condition = 'C',
      breakpoint_rejected = 'R',
      log_point = 'L',
    },
    lspkind = {
      Text = '',
      Method = '',
      Function = '',
      Constructor = '',
      Field = 'ﰠ',
      Variable = '',
      Class = 'ﴯ',
      Interface = '',
      Module = '',
      Property = 'ﰠ',
      Unit = '塞',
      Value = '',
      Enum = '',
      Keyword = '',
      Snippet = '',
      Color = '',
      File = '',
      Reference = '',
      Folder = '',
      EnumMember = '',
      Constant = '',
      Struct = 'פּ',
      Event = '',
      Operator = '',
      TypeParameter = '',
    },
  },
}
